### ISSUE TITLE
minor doc error

### ISSUE THREAD

**Issue by michael-stevens** [jib/mod_cookietrack#3]
Hi,

Reading DOCUMENTATION I saw:

 mod_cookietrack addresses this by optionally looking at the a header
  of your choosing (the industry standard is 'X-Forwarded-For') and
  using the right most IP in that to determine the remote IP.

surely it should be

"optionally looking at a header" rather than "optionally looking at the a header"?

**Comment by jib** [comment]
Thanks, fixed with https://github.com/jib/mod_cookietrack/commit/cd17687a84f8e9e967ddb0360840e380d85adeea
